export const GET_ERRORS = "GET_ERRORS";
export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";

// User
export const GET_YOUTUBE_DATA = "GET_YOUTUBE_DATA";
export const GET_MEDIUM_DATA = "GET_MEDIUM_DATA";
export const GET_GITHUB_DATA = "GET_GITHUB_DATA";
